name: Send scratch org email
description: Sends an email with the credentials of the newly created scratch org
author: Leon Kempers

inputs:
  displayUserJson:
    required: true
    description: JSON object representing the display user
  displayUrlJson:
    required: true
    description: JSON object representing the display URL
  sendgridApiKey:
    required: true
    description: Sendgrid API key
  fromEmail:
    required: true
    description: Address the email should be sent from
  toEmail:
    required: true
    description: Address the email should be sent to

runs:
  using: docker
  image: 'Dockerfile'