name: Get issue developer
description: This action extracts the developer's email address from a project card
author: Leon Kempers

inputs:
  token:
    description: GitHub token
    required: true
  cardNote:
    description: Note on the project card
    required: true
  issueUrl:
    description: URL of the issue associated with the project card
    required: true

outputs:
  developer:
    description: Email address of the developer

runs:
  using: docker
  image: 'Dockerfile'