name: Get issue developer
description: Extracts the assigned users' email addresses from the project card or issue
author: Leon Kempers

inputs:
  token:
    description: GitHub token
    required: true
  cardNote:
    description: Note on the project card
    required: true
  issueUrl:
    description: URL of the issue associated with the project card
    required: true

outputs:
  developer:
    description: Comma-separated list of email addresses of the assigned users

runs:
  using: docker
  image: 'Dockerfile'