name: Get issue developer
description: This action extracts the developer's email address from a project card
author: Leon Kempers

inputs:
  cardNote:
    required: true
    description: Note on the card
  issueUrl:
    required: true
    description: URL of the issue associated with the card

outputs:
  developer:
    description: Email address of the developer

runs:
  using: docker
  image: 'Dockerfile'