name: Send scratch org email
description: Sends an email with the credentials of the newly created scratch org
author: Leon Kempers

inputs:
  displayUserJson:
    description: JSON object representing the display user
    required: true
  displayUrlJson:
    description: JSON object representing the display URL
    required: true
  sendgridApiKey:
    description: Sendgrid API key
    required: true
  fromEmail:
    description: Address the email should be sent from
    required: true
  toEmails:
    description: Addresses the email should be sent to
    required: true

runs:
  using: docker
  image: 'Dockerfile'